2024.11.0으로 업그레이드
nekoplanet/misskey pull request #24
Opened 2024-11-19 10:41 UTC by HotoRas

## What

2024.11.0으로 업그레이드합니다.
- fixes error and resolves #23

## Why

- #23의 브랜치 수준 오류 수정

## Additional info (optional)

## Checklist
- [x] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [x] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [x] (If needed) Update CHANGELOG.md
- [x] (If possible) Add tests
- [ ] (If possible) Publish docker image

2024-11-19 10:45 UTC, HotoRas commented
@seojangho `pr-23`과 동일한 내용입니다. 앞으로 얘 위에서 작업 예정입니다.

2024-11-21 17:38 UTC, seojangho approved these changes
LGTM, 수고하셨습니다. :+1: 

2024.11.0-alpha.2 를 기반으로 한 diff를 리뷰하였고 특별히 고쳐야 할 사항은 없는것 같습니다.

2024-11-28 05:49 UTC, Hoto-Cocoa approved these changes
코니님의 approve 이후의 변경점에 대하여 리뷰합니다.

2024-11-28 05:50 UTC, Hoto-Cocoa commented
PR이 너무 커서 approve를 누르는 것에도 렉이 발생하네요...

2024-11-28 05:51 UTC, HotoRas commented
> PR이 너무 커서 approve를 누르는 것에도 렉이 발생하네요...

엄... 사실 단순한 미스키 업데이트(2024.9.0 -> 2024.11.0) 덩어리인데....

2024-11-28 06:10 UTC, Hoto-Cocoa requested changes
코드 받아서 라온님과 실행하고 테스트 해봤는데, 잘 동작하지만 비로그인 메인 페이지에 가입 버튼이 보여야 한다고 하시네요. 나머지 부분에는 별 문제가 없는 것 같다고 하시니 이 부분 고치고 리뷰 하고 병합하고 배포하면 될 것 같아요.

2024-11-28 06:11 UTC, Hoto-Cocoa commented
제가 그냥 commit 올릴까 했는데 개인 repository에 작업하셔서 nekoplanet/misskey에 committer 권한이 있어도 commit을 할 수가 없네요... 개인 repository에서 작업하시는 이유가 있나요?

2024-11-28 06:12 UTC, HotoRas commented
사실 따로 작업하는 게 PR 올릴 때 조금 편해요
업스트림으로 PR을 올리려고 하다 보니까도 있고..

2024-11-28 06:16 UTC, Hoto-Cocoa commented
> 사실 따로 작업하는 게 PR 올릴 때 조금 편해요 업스트림으로 PR을 올리려고 하다 보니까도 있고..

가능하면 nekoplanet에 올리는거면 nekoplanet 안에 있는게 좋을거라곤 생각해요... 👀

2024-11-28 06:22 UTC, HotoRas commented
잠깐만욤

2024-11-28 06:30 UTC, closed without merging