2024.11.0으로 업그레이드 (PR 재수정)
nekoplanet/misskey pull request #26
Opened 2024-11-28 06:27 UTC by HotoRas

## What

이중 삼중으로 브랜치 따기

## Why

디버깅 편의성

## Additional info (optional)

- resolves #24

## Checklist
- [ ] Read the [contribution guide](https://github.com/misskey-dev/misskey/blob/develop/CONTRIBUTING.md)
- [ ] Test working in a local environment
- [ ] (If needed) Add story of storybook
- [ ] (If needed) Update CHANGELOG.md
- [ ] (If possible) Add tests
- [ ] (If possible) Publish docker image

2024-11-28 06:52 UTC, Hoto-Cocoa requested changes
코드 받아서 라온님과 실행하고 테스트 해봤는데, 잘 동작하지만 비로그인 메인 페이지에 가입 버튼이 보여야 한다고 하시네요. 나머지 부분에는 별 문제가 없는 것 같다고 하시니 이 부분 고치고 리뷰 하고 병합하고 배포하면 될 것 같아요.

2024-11-28 07:25 UTC, seojangho commented
별 문제 없을것 같지만 오늘 밤에 한번 더 테스트 돌리고 review하겠습니다

2024-11-28 15:45 UTC, seojangho approved these changes
LGTM, 고생하셨습니다.

아래 사항에 대해서 머지 후 QA가 이루어지면 좋겠습니다. (제가 계획할게요)

- 프꾸 여러개 잘 연합되는지
- 가입이 아직 미승인된 유저가 할 수 있는 API/할 수 없는 API 확인
- 웹소켓 끊겼을때 메시지

긴 시간 고생하셨습니다. 특히 중간중간에 타입 any인거 고친부분이라거나 등등은 잘 갈무리해서 원판 미스키에도 PR 보내볼 수 있을것 같아요.

노고에 감사드립니다.

2024-12-07 07:31 UTC, HotoRas commented
머지하겠습니다. 고생하셨습니다.

2024-12-07 07:31 UTC, merged